// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfm66MINtSHsRVV7Cu8qnNjsB_aCF2eBM',
    appId: '1:399029662415:web:2b153d7ca7085db17f7dba',
    messagingSenderId: '399029662415',
    projectId: 'gestiontareas-3984e',
    authDomain: 'gestiontareas-3984e.firebaseapp.com',
    storageBucket: 'gestiontareas-3984e.appspot.com',
    measurementId: 'G-NMZG4KRZ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFsViuY6vr9apx369cVdjBTPrYZTtlS4',
    appId: '1:399029662415:android:46b754b89de9f39a7f7dba',
    messagingSenderId: '399029662415',
    projectId: 'gestiontareas-3984e',
    storageBucket: 'gestiontareas-3984e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC829Y2HBZnt4P8xcWHXH5NfT2zu1pgQRM',
    appId: '1:399029662415:ios:5a0acf5d53d81fd77f7dba',
    messagingSenderId: '399029662415',
    projectId: 'gestiontareas-3984e',
    storageBucket: 'gestiontareas-3984e.appspot.com',
    iosBundleId: 'com.example.gestionTareas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC829Y2HBZnt4P8xcWHXH5NfT2zu1pgQRM',
    appId: '1:399029662415:ios:5a0acf5d53d81fd77f7dba',
    messagingSenderId: '399029662415',
    projectId: 'gestiontareas-3984e',
    storageBucket: 'gestiontareas-3984e.appspot.com',
    iosBundleId: 'com.example.gestionTareas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfm66MINtSHsRVV7Cu8qnNjsB_aCF2eBM',
    appId: '1:399029662415:web:efd02ed607fc352b7f7dba',
    messagingSenderId: '399029662415',
    projectId: 'gestiontareas-3984e',
    authDomain: 'gestiontareas-3984e.firebaseapp.com',
    storageBucket: 'gestiontareas-3984e.appspot.com',
    measurementId: 'G-19Z5NKXSK9',
  );
}
